print("welcome to your card")
print("-------------------")
print("\n")
print("hi nice to meet you " + input("enter your name") + "! \n")
age =input("how old are you")
print("your age is " + age + "\n")
country = input("where do you live")
print("you live in: " + "("+ country +")" + " nice i would love a visit" + "\n")
nd =input("type your national id")
print("national ID:" + nd)
print("\n")
print("-------------------")
